"""Fetch open-job counts from Workable (server-side; avoids browser CORS).

Writes ``data/workable_counts.yaml`` (Greece ``incountry`` per apply.workable slug).
Consumed by ``scripts.generate_index`` and embedded in ``index.html``.

CI: run before ``generate_index`` (see ``.github/workflows/sync-on-main-merge.yaml`` —
push to ``main`` and daily 05:00 UTC).
"""

from __future__ import annotations

import json
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

from scripts.workable_apply_slug import extract_workable_apply_slug

YAML_PATH = Path("data/companies.yaml")
OUTPUT_PATH = Path("data/workable_counts.yaml")
DELAY_SEC = 0.15
TIMEOUT_SEC = 25
USER_AGENT = "awesome-greek-tech-jobs/1.0 (+https://github.com/leftkats/awesome-greek-tech-jobs)"


def parse_greece_incountry_count(data: object) -> int | None:
    """Use incountry for Greece; ignore global total.

    Workable usually returns ``country: \"Greece\"`` with ``incountry``.
    Some accounts omit ``country`` when counts are zero (only total/incountry).
    """
    if not isinstance(data, dict):
        return None
    n = data.get("incountry")
    if not isinstance(n, int) or n < 0:
        return None
    country = data.get("country")
    if country is None or (isinstance(country, str) and not country.strip()):
        return n
    if isinstance(country, str) and country.strip().casefold() == "greece":
        return n
    return None


def fetch_count(slug: str) -> int | None:
    path = urllib.parse.quote(slug, safe="")
    url = f"https://apply.workable.com/api/v1/accounts/{path}/jobs/count"
    req = urllib.request.Request(
        url,
        headers={"User-Agent": USER_AGENT, "Accept": "application/json"},
        method="GET",
    )
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT_SEC) as resp:
            data = json.load(resp)
    except (urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError, TimeoutError) as e:
        print(f"warn: {slug}: {e}", file=sys.stderr)
        return None
    n = parse_greece_incountry_count(data)
    if n is not None:
        return n
    print(f"warn: {slug}: missing Greece incountry in response", file=sys.stderr)
    return None


def main() -> int:
    with YAML_PATH.open(encoding="utf-8") as f:
        companies = yaml.safe_load(f)
    slugs: list[str] = []
    seen: set[str] = set()
    for c in companies or []:
        slug = extract_workable_apply_slug(c.get("careers_url"))
        if slug and slug not in seen:
            seen.add(slug)
            slugs.append(slug)

    accounts: dict[str, int | None] = {}
    for i, slug in enumerate(slugs):
        if i:
            time.sleep(DELAY_SEC)
        accounts[slug] = fetch_count(slug)

    total_open = sum(n for n in accounts.values() if isinstance(n, int))
    out = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "metric": "incountry_greece",
        "accounts": accounts,
        "total_open": total_open,
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as f:
        f.write(
            "# Workable Greece incountry open-role counts (generated by "
            "scripts/fetch_workable_counts)\n"
        )
        yaml.dump(
            out,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=100,
        )
    print(f"Wrote {OUTPUT_PATH} ({len(slugs)} accounts, total_open={total_open})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
